# Dockerfile.train

FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .

RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY train.py .
COPY model/ ./model/
COPY data_ingestion/ ./data_ingestion/
COPY preprocessing/ ./preprocessing/
COPY exp_log/ ./exp_log/

CMD ["python", "train.py"]
